from collections.abc import Iterator
from typing import Any, Literal, overload

from elftools.elf.sections import Section

class Relocation:
	@overload
	def __getitem__(self, name: Literal["r_offset", "r_info_sym", "r_info_type"]) -> int: ...
	@overload
	def __getitem__(self, name: str) -> Any: ...
	def is_RELA(self) -> bool: ...

class RelocationSection(Section):
	def is_RELA(self) -> bool: ...
	def iter_relocations(self) -> Iterator[Relocation]: ...
