ARM_CC_AL: int
ARM_CC_EQ: int
ARM_CC_GE: int
ARM_CC_GT: int
ARM_CC_HI: int
ARM_CC_HS: int
ARM_CC_LE: int
ARM_CC_LO: int
ARM_CC_LS: int
ARM_CC_LT: int
ARM_CC_MI: int
ARM_CC_NE: int
ARM_CC_PL: int
ARM_CC_VC: int
ARM_CC_VS: int
ARM_OP_IMM: int
ARM_OP_MEM: int
ARM_OP_REG: int
ARM_REG_LR: int
ARM_REG_PC: int
ARM_REG_R0: int
ARM_REG_R1: int
ARM_REG_R2: int
ARM_REG_R3: int
ARM_REG_R12: int
ARM_REG_SP: int
ARM_SFT_INVALID: int
ARM_SFT_LSL: int
