[manifest]
group-filter = ["-babblesim", "-optional", "-testing"]

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/zephyrproject-rtos/zephyr"
revision = "e560c91b1f74146baa3177b07b92a8733c60b7c7"
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-/MFCbUmllR5jJIPsNlc0eCy6VGmrsPPuAr6yPAnZ0gY="

[[manifest.projects]]
name = "cmsis_6"
url = "https://github.com/zephyrproject-rtos/CMSIS_6"
revision = "1c1840af7a7e757d6e2fec3ddb0e5ce0dfcc93c8"
path = "modules/hal/cmsis_6"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-IiE4Wzh1aWgPI589n7CaoDM8l25KtrRsGwUF0r74b18="

[manifest.self]
path = "manifest"
